### ISSUE TITLE
Finding lowest common divisor for nonStandard case

### ISSUE THREAD

**Issue by mboudreau** [vvideo/calc-aspect-ratio#1]
Just stumbled upon this project trying to do exactly what this library is doing, which is great!  Hard to find something like this in the sea of results when searching for `aspect ratio`.

Anywho, I noticed that the "default" case if it doesn't match anything is to keep the ratio to just `${width}:${height}` which is definitely one way of doing it, but like any good fractions, it should be reduced as much as possible using the greated common divisor of both numbers.  For example, this is what you'd do for the default case:

```
const gcd = (a:number = 0, b:number = 0) => { while (b) { [a, b] = [b, a % b]; } return a; };
const divisor = gcd(width, height);
const ratio = `${width/divisor}:${height/divisor}`;
```

So that if someone were to have a ridiculous aspect ratio of 10000 x 5000 it would reduce it to `2:1`.

I might just do a PR myself but figured I'd add this here as a reminder.  Thanks for your work.

**Comment by hcodes** [comment]
v1.3.0
